title: Muhammad Rusyadi Ramli

author:
  name: Muhammad Rusyadi Ramli
  email: ramli2@kth.se
  affiliation: KTH Royal Institute of Technology
  role: PhD Candidate
  location: Stockholm, Sweden

description: Personal academic website

theme: academic
defaultTheme: auto

logo:
  text: Muhammad Rusyadi Ramli

avatar:
  image: avatar.jpg
  gravatar: false

social:
  - icon: github
    icon_pack: fab
    link: https://github.com/ramli2
